# Generated by Django 6.0 on 2025-12-25 15:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonHoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_mon",
                    models.CharField(max_length=10, unique=True, verbose_name="Mã môn"),
                ),
                ("ten_mon", models.CharField(max_length=200, verbose_name="Tên môn")),
                (
                    "so_tin_chi",
                    models.IntegerField(default=4, verbose_name="Số tín chỉ"),
                ),
                (
                    "so_tiet_th",
                    models.IntegerField(default=30, verbose_name="Số tiết TH"),
                ),
                (
                    "hoc_ky",
                    models.CharField(
                        default="HK1-2024", max_length=20, verbose_name="Học kỳ"
                    ),
                ),
                (
                    "mo_ta",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Môn học",
                "verbose_name_plural": "Môn học",
                "db_table": "mon_hoc",
                "ordering": ["ma_mon"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Mã"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Sinh viên"),
                            ("instructor", "Giảng viên"),
                            ("lab_assistant", "Cán bộ phụ trách"),
                            ("admin", "Giáo vụ"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "class_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Lớp"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Chuyên môn"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Người dùng",
                "verbose_name_plural": "Người dùng",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="NhomThucHanh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_nhom", models.CharField(max_length=50, verbose_name="Tên nhóm")),
                ("suc_chua", models.IntegerField(default=40, verbose_name="Sức chứa")),
                (
                    "si_so_hien_tai",
                    models.IntegerField(default=0, verbose_name="Sĩ số hiện tại"),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("active", "Hoạt động"),
                            ("full", "Đã đủ"),
                            ("closed", "Đã đóng"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "giang_vien",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "instructor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nhom_giang_day",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mon_hoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nhom_th",
                        to="lab_management.monhoc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhóm thực hành",
                "verbose_name_plural": "Nhóm thực hành",
                "db_table": "nhom_thuc_hanh",
                "ordering": ["mon_hoc", "ten_nhom"],
                "unique_together": {("mon_hoc", "ten_nhom")},
            },
        ),
        migrations.CreateModel(
            name="PhongMay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_phong",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Mã phòng"
                    ),
                ),
                (
                    "ten_phong",
                    models.CharField(max_length=100, verbose_name="Tên phòng"),
                ),
                ("vi_tri", models.CharField(max_length=200, verbose_name="Vị trí")),
                ("suc_chua", models.IntegerField(verbose_name="Sức chứa")),
                ("so_hang", models.IntegerField(default=5, verbose_name="Số hàng")),
                ("so_cot", models.IntegerField(default=8, verbose_name="Số cột")),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("available", "Sẵn sàng"),
                            ("occupied", "Đang sử dụng"),
                            ("maintenance", "Bảo trì"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "can_bo_phu_trach",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "lab_assistant"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phong_phu_trach",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Phòng máy",
                "verbose_name_plural": "Phòng máy",
                "db_table": "phong_may",
                "ordering": ["ma_phong"],
            },
        ),
        migrations.CreateModel(
            name="MayTinh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_may", models.CharField(max_length=10, verbose_name="Số máy")),
                ("vi_tri_hang", models.IntegerField(verbose_name="Vị trí hàng")),
                ("vi_tri_cot", models.IntegerField(verbose_name="Vị trí cột")),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("available", "Sẵn sàng"),
                            ("in_use", "Đang sử dụng"),
                            ("maintenance", "Bảo trì"),
                            ("broken", "Hỏng"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("cpu", models.CharField(blank=True, max_length=100, null=True)),
                ("ram", models.CharField(blank=True, max_length=50, null=True)),
                ("storage", models.CharField(blank=True, max_length=50, null=True)),
                ("gpu", models.CharField(blank=True, max_length=100, null=True)),
                ("ngay_bao_tri_cuoi", models.DateField(blank=True, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phong_may",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="may_tinh",
                        to="lab_management.phongmay",
                    ),
                ),
            ],
            options={
                "verbose_name": "Máy tính",
                "verbose_name_plural": "Máy tính",
                "db_table": "may_tinh",
                "ordering": ["phong_may", "vi_tri_hang", "vi_tri_cot"],
                "unique_together": {("phong_may", "so_may")},
            },
        ),
        migrations.CreateModel(
            name="BuoiThucHanh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_buoi", models.IntegerField(verbose_name="Số buổi")),
                ("ngay_thuc_hien", models.DateField(verbose_name="Ngày thực hiện")),
                ("gio_bat_dau", models.TimeField(verbose_name="Giờ bắt đầu")),
                ("gio_ket_thuc", models.TimeField(verbose_name="Giờ kết thúc")),
                ("chu_de", models.CharField(max_length=200, verbose_name="Chủ đề")),
                (
                    "noi_dung",
                    models.TextField(blank=True, null=True, verbose_name="Nội dung"),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("upcoming", "Sắp diễn ra"),
                            ("ongoing", "Đang diễn ra"),
                            ("completed", "Đã hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("da_bo_tri_vi_tri", models.BooleanField(default=False)),
                ("da_diem_danh", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nhom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buoi_th",
                        to="lab_management.nhomthuchanh",
                    ),
                ),
                (
                    "phong_may",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buoi_th",
                        to="lab_management.phongmay",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buổi thực hành",
                "verbose_name_plural": "Buổi thực hành",
                "db_table": "buoi_thuc_hanh",
                "ordering": ["-ngay_thuc_hien", "-gio_bat_dau"],
                "unique_together": {("nhom", "so_buoi")},
            },
        ),
        migrations.CreateModel(
            name="DiemDanh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("present", "Có mặt"),
                            ("absent", "Vắng"),
                            ("late", "Muộn"),
                            ("excused", "Có phép"),
                        ],
                        max_length=20,
                    ),
                ),
                ("thoi_gian_diem_danh", models.DateTimeField(auto_now_add=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "buoi_th",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diem_danh",
                        to="lab_management.buoithuchanh",
                    ),
                ),
                (
                    "nguoi_diem_danh",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["instructor", "lab_assistant"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diem_danh_thuc_hien",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sinh_vien",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diem_danh",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Điểm danh",
                "verbose_name_plural": "Điểm danh",
                "db_table": "diem_danh",
                "unique_together": {("buoi_th", "sinh_vien")},
            },
        ),
        migrations.CreateModel(
            name="BoTriViTriNgoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngay_phan_cong", models.DateTimeField(auto_now_add=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "sinh_vien",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vi_tri_ngoi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "buoi_th",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bo_tri_vi_tri",
                        to="lab_management.buoithuchanh",
                    ),
                ),
                (
                    "may_tinh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phan_cong",
                        to="lab_management.maytinh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bố trí vị trí ngồi",
                "verbose_name_plural": "Bố trí vị trí ngồi",
                "db_table": "bo_tri_vi_tri_ngoi",
                "unique_together": {("buoi_th", "sinh_vien")},
            },
        ),
        migrations.CreateModel(
            name="CamThi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tong_so_buoi", models.IntegerField(verbose_name="Tổng số buổi")),
                ("so_buoi_vang", models.IntegerField(verbose_name="Số buổi vắng")),
                ("ty_le_vang", models.FloatField(verbose_name="Tỷ lệ vắng (%)")),
                ("ly_do", models.TextField(verbose_name="Lý do")),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("warning", "Cảnh báo"), ("banned", "Cấm thi")],
                        default="warning",
                        max_length=20,
                    ),
                ),
                (
                    "co_the_thi",
                    models.BooleanField(default=True, verbose_name="Có thể thi"),
                ),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nguoi_cap_nhat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cam_thi_cap_nhat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sinh_vien",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cam_thi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mon_hoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cam_thi",
                        to="lab_management.monhoc",
                    ),
                ),
                (
                    "nhom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cam_thi",
                        to="lab_management.nhomthuchanh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cấm thi",
                "verbose_name_plural": "Cấm thi",
                "db_table": "cam_thi",
                "unique_together": {("sinh_vien", "mon_hoc", "nhom")},
            },
        ),
        migrations.CreateModel(
            name="SinhVien_NhomThucHanh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngay_dang_ky", models.DateTimeField(auto_now_add=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("active", "Đang học"), ("dropped", "Đã hủy")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "nhom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sinh_vien",
                        to="lab_management.nhomthuchanh",
                    ),
                ),
                (
                    "sinh_vien",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dang_ky_nhom",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Đăng ký nhóm",
                "verbose_name_plural": "Đăng ký nhóm",
                "db_table": "sinh_vien_nhom",
                "unique_together": {("sinh_vien", "nhom")},
            },
        ),
    ]
